from typing import Any, Protocol


class IdentityRepositoryInterface(Protocol):
    def listar_usuarios(self) -> list[dict[str, Any]]: ...

    def crear_usuario(self, email: str, password_temporal: str) -> str: ...

    def asignar_rol(self, email: str, rol: str) -> None: ...

    def cambiar_rol_usuario(
        self, email: str, rol_antiguo: str, rol_nuevo: str
    ) -> None: ...

    def deshabilitar_usuario(self, email: str) -> None: ...

    def habilitar_usuario(self, email: str) -> None: ...

    def eliminar_usuario(self, email: str) -> None: ...
