from typing import Any, Protocol


class UsuarioInterface(Protocol):
    def listar_usuarios(self) -> list[dict[str, Any]]: ...

    def asignar_rol(self, email: str, rol: str) -> None: ...

    def remover_rol(self, email: str, rol: str) -> None: ...

    def eliminar_usuario(self, email: str) -> None: ...
